name: 'CI/CD Pipeline'
on:
  push:
    branches:
      - main
      - develop
      - master

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: list files
        run: ls
      - name: step2
        run: echo "This is step 2"
  
  docker-build-and-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t django-app:latest .
      
      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name django-container django-app:latest
      
      - name: Wait for container to be ready
        run: sleep 5

      - name: Test Django application
        uses: ./.github/actions/test_app
        with:
          filename: testfile.txt
              
      - name: Stop and remove container
        if: always()
        run: |
          docker stop django-container
          docker rm django-container
  
  call-reusable-workflow:
    needs: docker-build-and-test
    uses: ./.github/workflows/reusable_workflow.yml